#!/usr/bin/env python3
"""Build a compact OpenTTD baseset data archive plus a legacy-Emscripten-compatible loader.

The selected prebuilt OpenTTD glue predates the Emscripten version installed in CI.  The
current file_packager output downloads correctly but cannot resolve its individual run
dependencies in that older glue.  This generator deliberately uses only the runtime APIs
provided by the selected build: Module.addRunDependency, Module.removeRunDependency, FS,
and FS.writeFile.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def make_loader(entries: list[dict[str, int | str]], remote_name: str) -> str:
    manifest = json.dumps(entries, separators=(",", ":"))
    remote_json = json.dumps(remote_name)
    return f"""/* Generated by scripts/make-openttd-baseset-loader.py. */
(function() {{
  // This loader runs before openttd.js. Use the actual global Module object rather than
  // a function-local `var Module` (whose hoisting would create an isolated object).
  var moduleScope = typeof globalThis !== 'undefined' ? globalThis : window;
  var Module = moduleScope.Module = moduleScope.Module || {{}};
  var REMOTE_PACKAGE = {remote_json};
  var FILES = {manifest};
  var DEPENDENCY = 'retroplay-openttd-bundled-basesets';

  function mkdirp(path) {{
    var current = '';
    path.split('/').filter(Boolean).forEach(function(part) {{
      current += '/' + part;
      try {{ FS.mkdir(current); }} catch (_) {{}}
    }});
  }}

  function installPackage() {{
    Module.addRunDependency(DEPENDENCY);
    var url = Module.locateFile ? Module.locateFile(REMOTE_PACKAGE, '') : REMOTE_PACKAGE;
    fetch(url, {{ cache: 'no-cache' }})
      .then(function(response) {{
        if (!response.ok) throw new Error('Failed to load bundled OpenTTD data: ' + response.status);
        return response.arrayBuffer();
      }})
      .then(function(buffer) {{
        var bytes = new Uint8Array(buffer);
        FILES.forEach(function(file) {{
          var end = file.offset + file.length;
          if (end > bytes.length) throw new Error('Bundled OpenTTD data is truncated: ' + file.path);
          mkdirp(file.path.substring(0, file.path.lastIndexOf('/')));
          FS.writeFile(file.path, bytes.subarray(file.offset, end), {{ canOwn: true }});
        }});
        Module.removeRunDependency(DEPENDENCY);
      }})
      .catch(function(error) {{
        console.error('[OPENTTD] Bundled base-set load failed:', error);
        Module.removeRunDependency(DEPENDENCY);
        if (Module.onAbort) Module.onAbort(error.message || String(error));
      }});
  }}

  Module.preRun = Module.preRun || [];
  Module.preRun.push(installPackage);
}})();
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--data-output", type=Path, required=True)
    parser.add_argument("--loader-output", type=Path, required=True)
    parser.add_argument("--remote-name", default="openttd-basesets.data")
    args = parser.parse_args()

    source = args.source_dir.resolve()
    if not source.is_dir():
        raise SystemExit(f"Source directory does not exist: {source}")

    files = sorted(path for path in source.rglob("*") if path.is_file())
    if not files:
        raise SystemExit(f"Source directory has no files: {source}")

    args.data_output.parent.mkdir(parents=True, exist_ok=True)
    entries: list[dict[str, int | str]] = []
    offset = 0
    with args.data_output.open("wb") as output:
        for path in files:
            content = path.read_bytes()
            relative = path.relative_to(source).as_posix()
            entries.append({"path": f"/baseset/{relative}", "offset": offset, "length": len(content)})
            output.write(content)
            offset += len(content)

    args.loader_output.write_text(make_loader(entries, args.remote_name), encoding="utf-8")
    print(f"Packed {len(entries)} files / {offset} bytes into {args.data_output}")


if __name__ == "__main__":
    main()
